---
jobs:
  build:
    docker:
      -
        image: "circleci/android:api-25-alpha"
    environment:
      JVM_OPTS: "-Xmx3200m"
    steps:
      - checkout
      -
        restore_cache:
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
      -
        run:
          command: "./gradlew androidDependencies"
          name: "Download Dependencies"
      -
        save_cache:
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
          paths:
            - ~/.gradle
      -
        command: "echo \"my artifact file\" > /WorkingDir/artifact-1; mkdir /WorkingDir/artifacts; echo \"my artifact files in a dir\" > /WorkingDir/artifacts/artifact-2; echo \"done\";"
        name: "Creating Dummy Artifacts"
        run: ~
      -
        store_artifacts:
          destination: artifact-file
          path: /WorkingDir/artifact-1
    working_directory: /WorkingDir
version: 2
